server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    session:
      cookie:
        path: /
        name: JSESSIONID
        http-only: true
      timeout: 3600

spring:
  application:
    name: pnuBookStore

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URI}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: false

    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.starttls.enable: true
      mail:
        debug: false
        smtp:
          starttls:
            enable: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
      auto: false
    stack:
      auto: false
    s3:
      endpoint: ${S3_ENDPOINT}
      bucket: ${S3_BUCKET}