server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    session:
      cookie:
        path: /
        name: JSESSIONID
        http-only: true
      timeout: 3600

spring:
  application:
    name: testThymeLeaf

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudteam18?use_ssl=false
    username: root
    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

    open-in-view: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  data:
    redis:
      host: redis
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: pnuauction@gmail.com
    password: dwdkwjuyorcdvlxm
    properties:
      mail.smtp.starttls.enable: true
      mail:
        debug: false
        smtp:
          starttls:
            enable: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
      auto: false
    stack:
      auto: false
    s3:
      endpoint: ${S3_ENDPOINT}
      bucket: ${S3_BUCKET}


