---
# Source: argo-cd/templates/redis-secret-init/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    helm.sh/chart: argo-cd-7.1.1
    app.kubernetes.io/name: argocd-redis-secret-init
    app.kubernetes.io/instance: argo
    app.kubernetes.io/component: redis-secret-init
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v2.11.2"
  name: argo-argocd-redis-secret-init
  namespace: "default"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - argocd-redis
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
