services:
  mysql:
    image: mysql
    container_name: test_db
    env_file:
      - ./conf/mysql/.env
    ports:
      - "3306:3306"
    volumes:  #로컬 디비를 이용하기 위한 Volume 설정
      - ./conf/mysql/db:/var/lib/mysql


  redis:
    image: redis:latest
    ports:
      - '6379:6379'
