apiVersion: batch/v1
kind: Job
metadata:
  name: spring-batch-job
  namespace: web
spec:
  ttlSecondsAfterFinished: 50
  template:
    spec:
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: subject-job
        image: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-batch:latest
        envFrom:
            - secretRef:
                name: database-secret
      restartPolicy: OnFailure