# Elasticsearch 설정
clusterName: "elasticsearch"
nodeGroup: "master"

secret:
  password: qwer1234

# 노드 역할 설정
roles:
  - master
  - ingest
  - data

# 리플리카 수 설정
replicas: 1

# JVM 옵션 설정
esJavaOpts: "-Xmx1g -Xms1g"

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: true

# 리소스 요청 및 제한 설정
resources:
  requests:
    memory: "4Gi"
  limits:
    memory: "4Gi"

# 볼륨 설정
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 30Gi

# 서비스 설정
service:
  type: ClusterIP
  port: 9200

nodeSelector:
  node-group: "efk-group"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-group
          operator: In
          values:
          - "efk-group"