serviceAccount:
  create: true
  name: fluent-bit

nodeSelector:
  node-group: server-group

# tail은 파일을 읽는 방법
config:
  services: |
    [SERVICE]
        Daemon On
        Flush 5
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/nginx/access.log
        Parser nginx_access
        Tag nginx.access
        DB /var/log/flb_nginx_access.db
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
    
    [INPUT]
        Name tail
        Path /var/log/nginx/error.log
        Parser nginx_error
        Tag nginx.error
        DB /var/log/flb_nginx_error.db
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
  
  outputs: |
    [OUTPUT]
        Name es
        Match nginx.error
        Host elasticsearch-master
        Port 9200
        Index nginx_error_log
        Type _doc
        Logstash_Prefix nginx_error
        HTTP_User elastic
        HTTP_Passwd qwer1234
        Logstash_Format On
        Suppress_Type_Name On
        tls On
        tls.verify Off
        Retry_Limit False
        

    [OUTPUT]
        Name es
        Match nginx.access
        Host elasticsearch-master
        Port 9200
        Index nginx_access_log
        Type _doc
        Logstash_Prefix nginx_access
        HTTP_User elastic
        HTTP_Passwd qwer1234
        Logstash_Format On
        Suppress_Type_Name On
        tls On
        tls.verify Off
        Retry_Limit False

  customParsers: |
    [PARSER]
        Name   nginx_access
        Format regex
        Regex  ^(?<remote_addr>[^ ]*) - (?<remote_user>[^ ]*) \[(?<time_local>[^\]]*)\] "(?<request>[^"]*)" (?<status>[^ ]*) (?<body_bytes_sent>[^ ]*) "(?<http_referer>[^"]*)" "(?<http_user_agent>[^"]*)" "(?<http_x_forwarded_for>[^"]*)$
        Time_Key time_local
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   nginx_error
        Format regex
        Regex  ^(?<time>[^ ]+ [^ ]+) \[(?<level>[^\]]+)\] (?<pid>[0-9]+)#(?<tid>[0-9]+): \*(?<code>[0-9]+) (?<message>.*)$
        Time_Key time
        Time_Format %Y/%m/%d %H:%M:%S