spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloudteam18?use_ssl=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  application:
    name: PnuBookStoreBatchApplication

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false